name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Este flujo se ejecutará cuando haya un push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Establece que el flujo se ejecutará en un entorno Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clona tu repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Configura Node.js
        with:
          node-version: '20'  # Especifica la versión de Node.js que tu proyecto necesita

      - name: Install dependencies
        run: |
          npm install  # Instala las dependencias del proyecto

      - name: Build the project
        run: |
          npm run build  # Construye la aplicación (asegúrate de tener el script 'build' configurado en tu package.json)

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Tu token de autenticación de Netlify
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # El ID de tu sitio en Netlify
        run: |
          curl -sL https://github.com/netlify/cli/releases/download/v10.1.0/netlify-cli-linux-x64.tar.gz | tar xz -C /tmp
          /tmp/netlify deploy --prod --dir=dist  # Despliega la carpeta 'dist' (modifica si usas otra carpeta para la construcción)
